apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-app.fullname" . }}-proxy-nginx-conf
  namespace: nginx-ingress # set hardcore - todo mind how support namespace ingress nginx
data:
  default.conf: |  # set default.conf
    server {
      listen  {{ .Values.service.targetPort }};
      location / {
        proxy_pass http://{{ include "go-app.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local;
      }
    }
